name: b00965752_container_2
description: A microservice that calculates the sum and returns the result.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
